apiVersion: v1
kind: ConfigMap
metadata:
  name: appfastfood-configmap
data:

  MONGODB_HOST: "fastfood-docdb2-cluster.cluster-c4bgv5fkmppp.us-east-1.docdb.amazonaws.com"
  MONGODB_DATABASE: "appfastfood"
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
