apiVersion: v1
kind: Service
metadata:
  name: appfastfood-pedido
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: appfastfood-pedido
  ports:
    - port: 8080
      targetPort: 8080